name: tom_rt_native_semaphores
homepage: https://github.com/open-runtime/native_semaphores
repository: https://github.com/al-the-bear/native_semaphores
version: 1.0.1
description: Temporary fork of runtime_native_semaphores with missing Linux ARM ABI mappings added to fix cross-platform AOT compilation errors.
environment:
  sdk: '>=3.3.0 <4.0.0'


# Explicitly declare that this package works on all desktop platforms.
platforms:
  linux:
  macos:
  windows:

dependencies:
  ffi: ^2.1.2
  meta: ^1.15.0

dev_dependencies:
  test: ^1.25.5
  safe_int_id: ^1.1.1

